/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.sola.clients.swing.ui.cadastre;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.sola.clients.beans.administrative.BaUnitBean;
import org.sola.clients.beans.cadastre.CadastreObjectBean;
import org.sola.clients.beans.cadastre.MapSheetBean;
import org.sola.clients.beans.controls.SolaObservableList;
import org.sola.clients.beans.referencedata.DistrictBean;
import org.sola.clients.beans.referencedata.VdcBean;

/**
 *
 * @author KumarKhadka
 */
public class CadastreObjectPanel extends javax.swing.JPanel {

    private SolaObservableList<CadastreObjectBean> cadastreObjects;
    public static final String SELECT_CADASTRE_OBJECT_PROPERTY = "cadasterObjectSelect";

    public CadastreObjectPanel() {
        initComponents();
        rdbSearchByBoundaryItemStateChanged(null);
    }

    public SolaObservableList<CadastreObjectBean> getCadastreObjects() {
        if (cadastreObjects == null) {
            cadastreObjects = new SolaObservableList<CadastreObjectBean>();
        }
        return cadastreObjects;
    }

    public void setCadastreObjects(SolaObservableList<CadastreObjectBean> cadastreObjects) {
        if (cadastreObjects == null) {
            cadastreObjects = new SolaObservableList<CadastreObjectBean>();

        }
        this.cadastreObjects = cadastreObjects;
        firePropertyChange("cadastreObjects", null, this.cadastreObjects);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        districtListBean = new org.sola.clients.beans.referencedata.DistrictListBean();
        vdcListBean = new org.sola.clients.beans.referencedata.VdcListBean();
        cadastreObjectListBean = new org.sola.clients.beans.cadastre.CadastreObjectListBean();
        cadastreObjectBean = new org.sola.clients.beans.cadastre.CadastreObjectBean();
        districtListBean1 = new org.sola.clients.beans.referencedata.DistrictListBean();
        vdcListBean1 = new org.sola.clients.beans.referencedata.VdcListBean();
        mothListBean = new org.sola.clients.beans.administrative.MothListBean();
        locListBean = new org.sola.clients.beans.administrative.LocListBean();
        mapSheetListBean1 = new org.sola.clients.beans.cadastre.MapSheetListBean();
        mapSheetListBean2 = new org.sola.clients.beans.cadastre.MapSheetListBean();
        mapSheetListBean3 = new org.sola.clients.beans.cadastre.MapSheetListBean();
        mapSheetListBean4 = new org.sola.clients.beans.cadastre.MapSheetListBean();
        jPanel5 = new javax.swing.JPanel();
        rdbFreeSheet = new javax.swing.JRadioButton();
        rdbControSheet = new javax.swing.JRadioButton();
        rdbSearchByMapSheet = new javax.swing.JRadioButton();
        btnSearch2 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cmbMapNo1 = new javax.swing.JComboBox();
        jPanel17 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        cmbMapNo2 = new javax.swing.JComboBox();
        jPanel10 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        cmbMapNo3 = new javax.swing.JComboBox();
        jPanel9 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        cmbMapNo4 = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        cmbParcelNo1 = new javax.swing.JComboBox();
        jPanel12 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        cmbDistrict = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cmbVdc = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtWardNo = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtParcelNo = new javax.swing.JTextField();
        rdbSearchByBoundary = new javax.swing.JRadioButton();
        btnSearch1 = new javax.swing.JButton();

        buttonGroup2.add(rdbFreeSheet);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/sola/clients/swing/ui/cadastre/Bundle"); // NOI18N
        rdbFreeSheet.setText(bundle.getString("CadastreObjectPanel.rdbFreeSheet.text")); // NOI18N
        rdbFreeSheet.setEnabled(false);
        rdbFreeSheet.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rdbFreeSheetItemStateChanged(evt);
            }
        });

        buttonGroup2.add(rdbControSheet);
        rdbControSheet.setText(bundle.getString("CadastreObjectPanel.rdbControSheet.text")); // NOI18N
        rdbControSheet.setEnabled(false);
        rdbControSheet.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rdbControSheetItemStateChanged(evt);
            }
        });

        buttonGroup1.add(rdbSearchByMapSheet);
        rdbSearchByMapSheet.setText(bundle.getString("CadastreObjectPanel.rdbSearchByMapSheet.text")); // NOI18N
        rdbSearchByMapSheet.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rdbSearchByMapSheetItemStateChanged(evt);
            }
        });

        btnSearch2.setText(bundle.getString("CadastreObjectPanel.btnSearch2.text")); // NOI18N
        btnSearch2.setEnabled(false);
        btnSearch2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch2ActionPerformed(evt);
            }
        });

        jPanel7.setLayout(new java.awt.GridLayout(1, 5, 15, 2));

        jLabel5.setText(bundle.getString("CadastreObjectPanel.jLabel5.text")); // NOI18N

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${mapSheets}");
        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, mapSheetListBean1, eLProperty, cmbMapNo1);
        bindingGroup.addBinding(jComboBoxBinding);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(0, 90, Short.MAX_VALUE))
            .addComponent(cmbMapNo1, 0, 0, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbMapNo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel7.add(jPanel8);

        jLabel6.setText(bundle.getString("CadastreObjectPanel.jLabel6.text")); // NOI18N

        eLProperty = org.jdesktop.beansbinding.ELProperty.create("${mapSheets}");
        jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, mapSheetListBean2, eLProperty, cmbMapNo2);
        bindingGroup.addBinding(jComboBoxBinding);

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(0, 90, Short.MAX_VALUE))
            .addComponent(cmbMapNo2, 0, 0, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbMapNo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel7.add(jPanel17);

        jLabel9.setText(bundle.getString("CadastreObjectPanel.jLabel9.text")); // NOI18N

        eLProperty = org.jdesktop.beansbinding.ELProperty.create("${mapSheets}");
        jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, mapSheetListBean3, eLProperty, cmbMapNo3);
        bindingGroup.addBinding(jComboBoxBinding);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(0, 90, Short.MAX_VALUE))
            .addComponent(cmbMapNo3, javax.swing.GroupLayout.Alignment.TRAILING, 0, 0, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbMapNo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel7.add(jPanel10);

        jLabel7.setText(bundle.getString("CadastreObjectPanel.jLabel7.text")); // NOI18N

        eLProperty = org.jdesktop.beansbinding.ELProperty.create("${mapSheets}");
        jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, mapSheetListBean4, eLProperty, cmbMapNo4);
        bindingGroup.addBinding(jComboBoxBinding);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(0, 90, Short.MAX_VALUE))
            .addComponent(cmbMapNo4, 0, 0, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbMapNo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel7.add(jPanel9);

        jLabel8.setText(bundle.getString("CadastreObjectPanel.jLabel8.text")); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(0, 86, Short.MAX_VALUE))
            .addComponent(cmbParcelNo1, 0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbParcelNo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 17, Short.MAX_VALUE))
        );

        jPanel7.add(jPanel3);

        jPanel12.setLayout(new java.awt.GridLayout(1, 4, 15, 0));

        cmbDistrict.setEditable(true);
        cmbDistrict.setEnabled(false);

        eLProperty = org.jdesktop.beansbinding.ELProperty.create("${districts}");
        jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, districtListBean, eLProperty, cmbDistrict);
        bindingGroup.addBinding(jComboBoxBinding);
        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, districtListBean, org.jdesktop.beansbinding.ELProperty.create("${selectedDistrict}"), cmbDistrict, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        cmbDistrict.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbDistrictItemStateChanged(evt);
            }
        });

        jLabel1.setText(bundle.getString("CadastreObjectPanel.jLabel1.text")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addContainerGap(140, Short.MAX_VALUE))
            .addComponent(cmbDistrict, 0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbDistrict, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel12.add(jPanel2);

        jLabel2.setText(bundle.getString("CadastreObjectPanel.jLabel2.text")); // NOI18N

        cmbVdc.setEditable(true);
        cmbVdc.setEnabled(false);

        eLProperty = org.jdesktop.beansbinding.ELProperty.create("${vdcs}");
        jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, vdcListBean, eLProperty, cmbVdc);
        bindingGroup.addBinding(jComboBoxBinding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, vdcListBean, org.jdesktop.beansbinding.ELProperty.create("${selectedVdc}"), cmbVdc, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
            .addComponent(cmbVdc, 0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbVdc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel12.add(jPanel1);

        jLabel3.setText(bundle.getString("CadastreObjectPanel.jLabel3.text")); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addContainerGap(107, Short.MAX_VALUE))
            .addComponent(txtWardNo)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtWardNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel12.add(jPanel4);

        jLabel4.setText(bundle.getString("CadastreObjectPanel.jLabel4.text")); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addContainerGap(124, Short.MAX_VALUE))
            .addComponent(txtParcelNo)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtParcelNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel12.add(jPanel6);

        buttonGroup1.add(rdbSearchByBoundary);
        rdbSearchByBoundary.setText(bundle.getString("CadastreObjectPanel.rdbSearchByBoundary.text")); // NOI18N
        rdbSearchByBoundary.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rdbSearchByBoundaryItemStateChanged(evt);
            }
        });

        btnSearch1.setText(bundle.getString("CadastreObjectPanel.btnSearch1.text")); // NOI18N
        btnSearch1.setEnabled(false);
        btnSearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 739, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(rdbSearchByBoundary, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(rdbSearchByMapSheet)
                        .addGap(18, 18, 18)
                        .addComponent(rdbFreeSheet)
                        .addGap(28, 28, 28)
                        .addComponent(rdbControSheet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSearch2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbSearchByBoundary)
                    .addComponent(btnSearch1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbSearchByMapSheet)
                    .addComponent(rdbControSheet)
                    .addComponent(btnSearch2)
                    .addComponent(rdbFreeSheet))
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void rdbFreeSheetItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rdbFreeSheetItemStateChanged
        // TODO add your handling code here:
        if (rdbFreeSheet.isSelected()) {
            cmbMapNo1.setEnabled(true);
            cmbMapNo2.setEnabled(false);
            cmbMapNo3.setEnabled(false);
            cmbMapNo4.setEnabled(false);
            cmbParcelNo1.setEnabled(true);
            btnSearch2.setEnabled(true);
            loadFreeSheet();
        }
    }//GEN-LAST:event_rdbFreeSheetItemStateChanged
    private void loadFreeSheet() {
        mapSheetListBean1.loadMapSheetList(0);
    }

    private void loadControlSheet() {
        mapSheetListBean1.loadMapSheetList(1);
    }
    private void rdbSearchByBoundaryItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rdbSearchByBoundaryItemStateChanged
        // TODO add your handling code here:
        if (rdbSearchByBoundary.isSelected()) {
            cmbDistrict.setEnabled(true);
            cmbVdc.setEnabled(true);
            txtWardNo.setEnabled(true);
            txtParcelNo.setEnabled(true);
            btnSearch1.setEnabled(true);
            rdbFreeSheet.setSelected(false);
            rdbControSheet.setSelected(false);
            rdbFreeSheet.setEnabled(false);
            rdbControSheet.setEnabled(false);
            cmbMapNo1.setEnabled(false);
            cmbMapNo2.setEnabled(false);
            cmbMapNo3.setEnabled(false);
            cmbMapNo4.setEnabled(false);
            cmbParcelNo1.setEnabled(false);
            btnSearch2.setEnabled(false);
        }

    }//GEN-LAST:event_rdbSearchByBoundaryItemStateChanged

    private void rdbSearchByMapSheetItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rdbSearchByMapSheetItemStateChanged
        // TODO add your handling code here:
        if (rdbSearchByMapSheet.isSelected()) {
            cmbDistrict.setEnabled(false);
            cmbVdc.setEnabled(false);
            txtWardNo.setEnabled(false);
            txtParcelNo.setEnabled(false);
            btnSearch1.setEnabled(false);

            rdbFreeSheet.setSelected(false);
            rdbControSheet.setSelected(false);
            rdbFreeSheet.setEnabled(true);
            rdbControSheet.setEnabled(true);
            btnSearch2.setEnabled(true);
        }
    }//GEN-LAST:event_rdbSearchByMapSheetItemStateChanged

    private void cmbDistrictItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbDistrictItemStateChanged
        // TODO add your handling code here:
        try {
            if (cmbDistrict.getSelectedItem() == null) {
                return;
            }

            DistrictBean district = (DistrictBean) cmbDistrict.getSelectedItem();
            if (district != null) {
                String districCode = district.getCode();
                vdcListBean.loadList(false, districCode);
                cmbVdc.setSelectedIndex(-1);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_cmbDistrictItemStateChanged

    private void fireParcelSelect(CadastreObjectBean cadastreObject) {
        if (cadastreObject == null) {
            JOptionPane.showMessageDialog(this, "Could not find the specified parcel.");
            return;
        }
        firePropertyChange(SELECT_CADASTRE_OBJECT_PROPERTY, null, cadastreObject);
    }

    private void btnSearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch1ActionPerformed
        //invoke method.
        try {
            VdcBean vdc = (VdcBean) cmbVdc.getSelectedItem();
            fireParcelSelect(CadastreObjectBean.getCadastreObjectByVdcWardParcel(vdc.getCode(), txtWardNo.getText().toString(), Integer.parseInt(txtParcelNo.getText().toString())));
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnSearch1ActionPerformed

    private void btnSearch2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch2ActionPerformed
        try {
            MapSheetBean map = (MapSheetBean) cmbMapNo1.getSelectedItem();
            fireParcelSelect(CadastreObjectBean.getCadastreObjectByMapAndParcelNo(map.getId().toString(), Integer.parseInt(cmbParcelNo1.getSelectedItem().toString())));
        } catch (Exception ex) {
            Logger.getLogger(CadastreObjectPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSearch2ActionPerformed

    private void rdbControSheetItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rdbControSheetItemStateChanged
        // TODO add your handling code here:
        if (rdbControSheet.isSelected()) {
            cmbMapNo1.setEnabled(true);
            cmbMapNo2.setEnabled(true);
            cmbMapNo3.setEnabled(true);
            cmbMapNo4.setEnabled(true);
            cmbParcelNo1.setEnabled(true);
            btnSearch2.setEnabled(true);
            loadControlSheet();
        }
    }//GEN-LAST:event_rdbControSheetItemStateChanged

    private void baUnitOperation(SolaObservableList<BaUnitBean> baUnits) {
        BaUnitBean baUnit;
        if (baUnits.size() > 0) {
            baUnit = baUnits.get(0);
            baUnitFinalOperation(baUnit);
        }
    }

    private void baUnitFinalOperation(BaUnitBean baUnitBean) {
        SolaObservableList<CadastreObjectBean> cadObjLst = new SolaObservableList<CadastreObjectBean>();
//        for (CadastreObjectBean cadBean : baUnitBean.getCadastreObjectList()) {
//            cadObjLst.add(cadBean);
//        }
        cadastreObjectOperation(cadObjLst);
    }

    private void cadastreObjectOperation(SolaObservableList<CadastreObjectBean> cadastreObjectBeans) {
        cadastreObjects.clear();
        setCadastreObjects(cadastreObjectBeans);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch1;
    private javax.swing.JButton btnSearch2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private org.sola.clients.beans.cadastre.CadastreObjectBean cadastreObjectBean;
    private org.sola.clients.beans.cadastre.CadastreObjectListBean cadastreObjectListBean;
    private javax.swing.JComboBox cmbDistrict;
    private javax.swing.JComboBox cmbMapNo1;
    private javax.swing.JComboBox cmbMapNo2;
    private javax.swing.JComboBox cmbMapNo3;
    private javax.swing.JComboBox cmbMapNo4;
    private javax.swing.JComboBox cmbParcelNo1;
    private javax.swing.JComboBox cmbVdc;
    private org.sola.clients.beans.referencedata.DistrictListBean districtListBean;
    private org.sola.clients.beans.referencedata.DistrictListBean districtListBean1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private org.sola.clients.beans.administrative.LocListBean locListBean;
    private org.sola.clients.beans.cadastre.MapSheetListBean mapSheetListBean1;
    private org.sola.clients.beans.cadastre.MapSheetListBean mapSheetListBean2;
    private org.sola.clients.beans.cadastre.MapSheetListBean mapSheetListBean3;
    private org.sola.clients.beans.cadastre.MapSheetListBean mapSheetListBean4;
    private org.sola.clients.beans.administrative.MothListBean mothListBean;
    private javax.swing.JRadioButton rdbControSheet;
    private javax.swing.JRadioButton rdbFreeSheet;
    private javax.swing.JRadioButton rdbSearchByBoundary;
    private javax.swing.JRadioButton rdbSearchByMapSheet;
    private javax.swing.JTextField txtParcelNo;
    private javax.swing.JTextField txtWardNo;
    private org.sola.clients.beans.referencedata.VdcListBean vdcListBean;
    private org.sola.clients.beans.referencedata.VdcListBean vdcListBean1;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
